name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASS }}   # o DOCKERHUB_TOKEN si así lo llamaste
        run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build the Docker image
        run: |
          docker build ./randomquotes-flask-master \
            --file ./randomquotes-flask-master/Dockerfile \
            --tag luisnp10/express-randomquotes:latest

      - name: Push Docker image
        run: |
          docker push luisnp10/express-randomquotes:latest
