name: Docker Image CI
on:
 push:
 branches: [ master ]
 pull_request:
 branches: [ master ]
jobs:
 build:
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout@v4
 - name: docker login
 env:
 DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
 DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}}
 run: |
 docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
 - name: Build the Docker image
 run: docker build . --file Dockerfile --tag luisnp10/express-randomquotes:latest

 - name: Docker Push
 run: docker push luisnp10/express-randomquotes
